// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lux-dashboard/Atelier.tsx": () => import("../components/mockups/lux-dashboard/Atelier.tsx"),
  "./components/mockups/lux-dashboard/Cockpit.tsx": () => import("../components/mockups/lux-dashboard/Cockpit.tsx"),
  "./components/mockups/lux-dashboard/Vault.tsx": () => import("../components/mockups/lux-dashboard/Vault.tsx")
};
